server:
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    password: kieuduyen20112000
    url: jdbc:mysql://localhost:3306/techthing
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

